### ISSUE TITLE
Boot loop on Aura (non-HD)

### ISSUE THREAD

**Issue by KenMacD** [dbeinder/kobo-nightmode#1]
Installed build 10 on a new non-HD Aura and the system will not boot.

Other users seem to have hit the same issue:

http://www.mobileread.com/forums/showthread.php?t=229579

**Comment by KenMacD** [comment]
Anything I can do to help move this along? I have telnet running on my Aura now, I compiled with debug and I get the following log:

```
# cat screenInvertLog 
ScreenInverter: Hooked to /usr/local/Kobo/nickel!
ScreenInverter: Removed LD_PRELOAD!
ScreenInverter: Reading device type: phoenix
ScreenInverter: No HW inversion support, falling back to SW.
ScreenInverter: mmap'ed the virtual framebuffer!
ScreenInverter: Got screen resolution: 1024x758 @16BPP
ScreenInverter: Config file invalid or not found, using defaults
ScreenInverter: Could no stat() config file
ScreenInverter: mmap'ed the virtual framebuffer!
ScreenInverter: update: type:full, flags:0x0, size:1024x758 (100% updated)
```

**Comment by KenMacD** [comment]
Think I figured this one out. It was the calls to mmap() that weren't calling the original method, but the patched method instead. This resulted in the wrong values being returned and later a segfault.

Tested the fix with a debug version run manually on a Kobo Aura. I haven't built a full package and installed it yet.

**Comment by KenMacD** [comment]
Just tested a full build and KoboRoot.tgz worked with this version, although it does seem to refresh the screen and flash to a white background on every page flip.

**Comment by dbeinder** [comment]
many thanks for finding it, i was totally looking at the wrong places for the problem ^^

about the refresh, i can not reproduce it on my glo, but i added a few more debug messages, in case it has something to do with the custom refresh in nightmode

**Comment by KenMacD** [comment]
No problem, glad to help. I spent quite a bit of time looking in the wrong places too. For a bit I was convinced the nickel code was somehow running an mmap() before the constructor finished, maybe with some higher priority multithreaded constructor, lol.

I'll do some more testing on the flashing now that I have the build environment and let you know.

Thanks for making this!

**Comment by KenMacD** [comment]
Looks like the flashing was just the screen being refreshed. https://github.com/dbeinder/kobo-nightmode/blob/master/installer/mnt/onboard/.kobo/nightmode.ini#L11 has it set to update every page on a new install. Changed the settings and it's perfect now.

**Comment by dbeinder** [comment]
That's strange, a value of 0 should actually disable the custom refresh:
https://github.com/dbeinder/kobo-nightmode/blob/master/src/screenInv.c#L421

**Comment by only1thor** [comment]
Just tried to install on my non-HD kobo, and the "restarting" screen has been there for quite a while. 30min ish. How long should I wait and what is the best course of action if it is locked up? Hold the power button?

**Comment by only1thor** [comment]
Found the solution here: 
http://www.mobileread.com/forums/showthread.php?t=212162&page=39
all i had to do was hold the powerbutton so it was off, than connect it to the usb power. 
Booted right up.
