### ISSUE TITLE
Doesn't work on Kobo Aura 

### ISSUE THREAD

**Issue by cheeoh** [dbeinder/kobo-nightmode#11]
This worked for me last year, but I recently had to factory reset my eReader. Then it updated to software version 4.5.9587. I installed the nightmode as instructed, but it doesn't change to nightmode after long-pressing the light button.

**Comment by KenMacD** [comment]
This one no longer works, you're now looking for https://github.com/gtalusan/kobo-nightmode

**Comment by cheeoh** [comment]
Thank you so much!!! I really appreciate your help and quick response :)
