### ISSUE TITLE
Glo loosing USB-connection

### ISSUE THREAD

**Issue by ghost** [dbeinder/kobo-nightmode#3]
Hello,

today I'd updated my Kobo Glo to 3.1.1 (761b066420, 11.12.13) and installed the nightmode for the first time afterwards.

Nightmode worked fine, but my glo was loosing the USB-connection after approximately 10 seconds and was rebooting automatically. Same behaviour on two PCs (both with Windows XP)

I managed to load the uninstallation-file to my Kobo in the short period the USB-connection was established. Kobo installed and rebooted. Afterwards the USB-connection was working flawlessly.

My Glo is one of the earlyer models with the blueish light.

With kind regards

kobo-ld

**Comment by dbeinder** [comment]
Looking at the mobileread thread, I suppose your problem has been solved by using KenMacD's build?
I have been rather busy and forgot to update the github page with build11 (which should be equivalent to KenMacD's), but I'll do that right now.
